import type { SiteCopy } from './site-content';
import type { Locale } from './i18n';

// Complete the visible copy for languages whose original v7.1 objects inherited English or Polish sections.
// Keep the same product groups; none of these descriptions specify unverified numeric capabilities.
const overrides: Record<Locale, Partial<SiteCopy>> = {
  pl: {},
  en: {
    about: { title: 'SilvoTech is a manufacturer', lead: 'We combine production, material selection, quality control, logistics and a Warsaw warehouse in one B2B service model.', pillars: [
      { title: 'Manufacturing', text: 'Standard production runs and custom-made components.' },
      { title: 'Materials and processes', text: 'Selecting a solution for the application requirements.' },
      { title: 'Quality control', text: 'Checking dimensions, workmanship and agreed requirements.' },
      { title: 'Warehouse and logistics', text: 'Agreed stock for customers with recurring demand.' },
    ] },
    productionPage: { title: 'Production', lead: 'See how we plan and deliver standard and custom products.', stages: [
      { title: 'Product review', text: 'We assess material, geometry, tolerances and expected volume.' },
      { title: 'Process preparation', text: 'We choose the process, tooling and production parameters.' },
      { title: 'Extrusion and finishing', text: 'We carry out manufacturing and prepare the parts.' },
      { title: 'Quality control', text: 'We check the agreed characteristics before dispatch.' },
      { title: 'Packaging', text: 'We agree packaging with the customer for the product and delivery.' },
      { title: 'Warehouse', text: 'We can hold an agreed stock in Warsaw for recurring products.' },
    ] },
    docs: { title: 'Quality and documentation', lead: 'We agree checks and documentation according to the product, material and application.', items: [
      { title: 'Dimensional checks', text: 'Checking the product against the agreed parameters.' },
      { title: 'Material identification', text: 'Selecting and confirming the material for the application.' },
      { title: 'Documentation', text: 'Declarations, test results or specifications are supplied as agreed.' },
      { title: 'Test sample', text: 'Where needed, we prepare a sample before series production.' },
    ] },
  },
  de: {
    nav: { home: 'Startseite', products: 'Möglichkeiten', production: 'Produktion', about: 'Über uns', cooperation: 'Zusammenarbeit', documents: 'Qualität', contact: 'Kontakt', cta: 'Produktion anfragen', menu: 'Menü öffnen', language: 'Sprache wählen' },
    hero: { eyebrow: 'B2B-Fertigung nach Ihren Anforderungen', title: 'Hersteller von Silikon-, Gummi- und Kunststoffprodukten', lead: 'Schläuche, Dichtungen, Profile und Sonderteile nach Muster, Maßen oder Zeichnung. Beschreiben Sie die Anwendung, und wir prüfen die Machbarkeit.', proof: 'Direkte Fertigung • Individuelle Lösungen • Lager in Warschau', primary: 'Anfrage senden', secondary: 'Möglichkeiten ansehen' },
    products: { label: 'Was wir fertigen', title: 'Beispiele für Produktgruppen', lead: 'Dies sind Beispiele unserer Möglichkeiten, kein geschlossener Katalog. Maße, Material und Dokumentation stimmen wir für jede Anwendung ab.', items: [
      { title: 'Schläuche und Leitungen', text: 'Aus Silikon, Gummi und weiteren technischen Werkstoffen. Standardausführung oder nach Spezifikation.' },
      { title: 'Dichtungen', text: 'Aus Silikon, Gummi, EPDM und NBR. Fertigung nach Muster oder Zeichnung.' },
      { title: 'Profile', text: 'Silikon-, Gummi- und EPDM-Profile, auch mit individuellem Querschnitt.' },
      { title: 'Platten und Bahnen', text: 'Materialien mit abgestimmter Dicke, Härte und Abmessung.' },
      { title: 'Technische Bauteile', text: 'Individuelle Teile entsprechend den Anforderungen der Anwendung.' },
      { title: 'Kunststoffteile', text: 'Bauteile nach den technischen Anforderungen des Kunden.' },
      { title: 'Sonderanfertigungen', text: 'Wir prüfen auch Produkte außerhalb eines Standardsortiments.' },
    ], otherTitle: 'Ein anderes Produkt?', otherText: 'Senden Sie Muster, Foto, Maße oder Zeichnung. Wir prüfen die Fertigungsmöglichkeit.', otherCta: 'Machbarkeit anfragen' },
    materials: { label: 'Werkstoffe', title: 'Material für die Einsatzbedingungen', lead: 'Wir klären das Material anhand von Temperatur, Medium, Belastung, Umgebung und erforderlichen Unterlagen.', items: [
      { title: 'Silikon', text: 'Elastische Teile für technische und temperaturabhängige Anwendungen.' },
      { title: 'Gummi', text: 'Technische Produkte mit auf die Anwendung abgestimmten Eigenschaften.' },
      { title: 'EPDM', text: 'Profile und Dichtungen für anspruchsvolle Umgebungsbedingungen.' },
      { title: 'NBR', text: 'Technische Teile für Anwendungen etwa mit Ölen und Kraftstoffen.' },
      { title: 'Kunststoffe', text: 'Teile und Komponenten nach technischer Dokumentation.' },
    ] },
    capabilities: { label: 'Fertigungsmöglichkeiten', title: 'Verfahren passend zum Produkt', text: 'Wir prüfen Geometrie, Werkstoff, Toleranzen, Betriebsbedingungen und Stückzahl. Danach legen wir Verfahren und Kontrollen fest.', bullets: ['Extrusion von Profilen und Schläuchen', 'Bearbeitung und Vorbereitung von Teilen', 'Fertigung nach Muster oder Unterlagen', 'Maß- und Qualitätskontrolle', 'Verpackung nach Kundenbedarf', 'Serienfertigung und regelmäßige Lieferung'], cta: 'Produktion ansehen' },
    partner: { label: 'Service in Europa', title: 'Lieferungen an Unternehmen in Europa', text: 'Wir koordinieren Fertigung, Qualitätskontrolle und Logistik mit einem Ansprechpartner bei SilvoTech.', materials: ['Silikon', 'Gummi', 'EPDM', 'NBR', 'Kunststoffe', 'Machbarkeit prüfen'] },
    process: { label: 'Zusammenarbeit', title: 'Vom Muster zur regelmäßigen Lieferung', steps: [
      { title: 'Anfrage', text: 'Sie senden Muster, Foto, Maße oder Zeichnung.' },
      { title: 'Prüfung', text: 'Wir prüfen die Machbarkeit und kalkulieren das Projekt.' },
      { title: 'Angebot und Muster', text: 'Wir erstellen ein Angebot und bei Bedarf ein Prüfmuster.' },
      { title: 'Fertigung', text: 'Nach Freigabe planen und starten wir die Produktion.' },
      { title: 'Lager', text: 'Für regelmäßigen Bedarf können wir Bestand in Warschau vorhalten.' },
      { title: 'Lieferung', text: 'Vereinbarter Lagerbestand kann auch innerhalb von 24 Stunden versandt werden.' },
    ] },
    form: { label: 'B2B-Anfrage', title: 'Hersteller anfragen', lead: 'Beschreiben Sie das Teil oder fügen Sie Foto und Zeichnung bei. Wir prüfen die Machbarkeit und klären technische Fragen.', company: 'Unternehmen', name: 'Vor- und Nachname', email: 'E-Mail', phone: 'Telefon', product: 'Produkt', material: 'Material', dimensions: 'Abmessungen', quantity: 'Menge', message: 'Weitere Angaben', photo: 'Foto anhängen', drawing: 'Zeichnung anhängen', optional: 'optional', privacy: 'Dateien: JPG, PNG, WEBP oder PDF, jeweils maximal 4 MB.', submit: 'Fertigungsanfrage senden', sending: 'Wird gesendet…', successTitle: 'Anfrage gesendet', successText: 'Vielen Dank. Wir melden uns nach der ersten Prüfung.', errorRequired: 'Bitte füllen Sie die Pflichtfelder aus.', errorEmail: 'Bitte geben Sie eine gültige E-Mail-Adresse an.', errorFile: 'Der Anhang hat ein ungültiges Format oder überschreitet 4 MB.', errorSend: 'Die Anfrage konnte nicht gesendet werden. Versuchen Sie es erneut oder rufen Sie uns an.' },
    about: { title: 'SilvoTech ist Hersteller', lead: 'Wir verbinden Fertigung, Materialauswahl, Qualitätskontrolle, Logistik und Lager in Warschau für B2B-Kunden.', pillars: [
      { title: 'Fertigung', text: 'Standardserien und individuell gefertigte Teile.' },
      { title: 'Werkstoffe und Verfahren', text: 'Auswahl passend zu den Anforderungen der Anwendung.' },
      { title: 'Qualitätskontrolle', text: 'Prüfung von Maßen, Ausführung und vereinbarten Anforderungen.' },
      { title: 'Lager und Logistik', text: 'Vereinbarter Bestand bei regelmäßigem Bedarf.' },
    ] },
    productionPage: { title: 'Produktion', lead: 'So planen und fertigen wir Standard- und Sonderprodukte.', stages: [
      { title: 'Produktprüfung', text: 'Wir bewerten Werkstoff, Geometrie, Toleranzen und Stückzahl.' },
      { title: 'Prozessvorbereitung', text: 'Wir wählen Verfahren, Werkzeuge und Fertigungsparameter.' },
      { title: 'Extrusion und Bearbeitung', text: 'Wir fertigen und bearbeiten die Teile.' },
      { title: 'Qualitätskontrolle', text: 'Vor dem Versand prüfen wir die vereinbarten Merkmale.' },
      { title: 'Verpackung', text: 'Die Verpackung stimmen wir auf Produkt und Transport ab.' },
      { title: 'Lager', text: 'Für wiederkehrende Produkte kann Bestand in Warschau bereitstehen.' },
    ] },
    docs: { title: 'Qualität und Dokumentation', lead: 'Prüfungen und Dokumente stimmen wir auf Produkt, Material und Anwendung ab.', items: [
      { title: 'Maßkontrolle', text: 'Prüfung anhand der vereinbarten Parameter.' },
      { title: 'Materialzuordnung', text: 'Auswahl und Bestätigung des Materials für die Anwendung.' },
      { title: 'Dokumentation', text: 'Erklärungen, Prüfergebnisse oder Spezifikationen nach Vereinbarung.' },
      { title: 'Prüfmuster', text: 'Bei Bedarf fertigen wir vor der Serie ein Muster.' },
    ] },
    footer: { summary: 'Fertigung und regelmäßige Lieferungen für B2B-Kunden in Polen und Europa.', company: 'Unternehmen', offer: 'Möglichkeiten', contact: 'Kontakt', rights: 'Alle Rechte vorbehalten.', privacy: 'Datenschutzerklärung' },
  },
  cz: {
    nav: { home: 'Úvod', products: 'Možnosti', production: 'Výroba', about: 'O nás', cooperation: 'Spolupráce', documents: 'Kvalita', contact: 'Kontakt', cta: 'Poptat výrobu', menu: 'Otevřít menu', language: 'Vybrat jazyk' },
    hero: { eyebrow: 'B2B výroba podle vašich požadavků', title: 'Výrobce silikonových, pryžových a plastových výrobků', lead: 'Hadice, těsnění, profily a zakázkové díly podle vzorku, rozměrů nebo výkresu. Popište použití a my prověříme možnost výroby.', proof: 'Přímá výroba • Zakázková řešení • Sklad ve Varšavě', primary: 'Odeslat poptávku', secondary: 'Zobrazit možnosti' },
    products: { label: 'Co vyrábíme', title: 'Příklady skupin výrobků', lead: 'Jde o příklady našich možností, nikoli uzavřený katalog. Rozměry, materiál a dokumentaci upřesňujeme pro každé použití.', items: [
      { title: 'Hadice a vedení', text: 'Silikonové, pryžové a technické. Standardní nebo podle specifikace.' },
      { title: 'Těsnění', text: 'Ze silikonu, pryže, EPDM a NBR. Výroba podle vzorku nebo výkresu.' },
      { title: 'Profily', text: 'Silikonové, pryžové a EPDM profily včetně individuálních průřezů.' },
      { title: 'Desky a pláty', text: 'Materiály s dohodnutou tloušťkou, tvrdostí a rozměry.' },
      { title: 'Technické díly', text: 'Individuální díly podle požadavků konkrétní aplikace.' },
      { title: 'Plastové díly', text: 'Výrobky podle technických požadavků zákazníka.' },
      { title: 'Zakázková výroba', text: 'Prověříme i výrobky mimo standardní sortiment.' },
    ], otherTitle: 'Potřebujete jiný výrobek?', otherText: 'Pošlete vzorek, fotografii, rozměry nebo výkres. Prověříme možnost výroby.', otherCta: 'Prověřit možnost výroby' },
    materials: { label: 'Materiály', title: 'Materiál podle provozních podmínek', lead: 'Materiál upřesňujeme podle teploty, média, zatížení, prostředí a požadované dokumentace.', items: [
      { title: 'Silikon', text: 'Pružné díly pro technické a teplotně náročné aplikace.' },
      { title: 'Pryž', text: 'Technické výrobky s parametry podle konkrétního použití.' },
      { title: 'EPDM', text: 'Profily a těsnění pro náročné podmínky prostředí.' },
      { title: 'NBR', text: 'Technické díly také pro aplikace s oleji a palivy.' },
      { title: 'Plasty', text: 'Díly a komponenty podle technické dokumentace.' },
    ] },
    capabilities: { label: 'Výrobní možnosti', title: 'Technologie podle výrobku', text: 'Posuzujeme geometrii, materiál, tolerance, pracovní podmínky a množství. Podle toho volíme postup a kontroly.', bullets: ['Extruze profilů a hadic', 'Opracování a příprava dílů', 'Výroba podle vzorku nebo dokumentace', 'Rozměrová a kvalitativní kontrola', 'Balení podle potřeb zákazníka', 'Sériová výroba a pravidelné dodávky'], cta: 'Prohlédnout výrobu' },
    partner: { label: 'Evropská spolupráce', title: 'Dodávky firmám v Evropě', text: 'Výrobu, kontrolu kvality a logistiku koordinujeme s jednou kontaktní osobou v SilvoTech.', materials: ['Silikon', 'Pryž', 'EPDM', 'NBR', 'Plasty', 'Prověříme možnost výroby'] },
    process: { label: 'Spolupráce', title: 'Od vzorku k pravidelným dodávkám', steps: [
      { title: 'Poptávka', text: 'Pošlete vzorek, fotografii, rozměry nebo výkres.' },
      { title: 'Posouzení', text: 'Prověříme proveditelnost a připravíme kalkulaci.' },
      { title: 'Nabídka a vzorek', text: 'Připravíme nabídku a podle potřeby zkušební vzorek.' },
      { title: 'Výroba', text: 'Po schválení naplánujeme a zahájíme výrobu.' },
      { title: 'Sklad', text: 'Pro pravidelný odběr můžeme držet zásobu ve Varšavě.' },
      { title: 'Dodávka', text: 'Dohodnuté skladové zboží lze odeslat i do 24 hodin.' },
    ] },
    form: { label: 'B2B poptávka', title: 'Poptat u výrobce', lead: 'Popište výrobek nebo přiložte fotografii a výkres. Prověříme možnost výroby a případné technické otázky.', company: 'Firma', name: 'Jméno a příjmení', email: 'E-mail', phone: 'Telefon', product: 'Výrobek', material: 'Materiál', dimensions: 'Rozměry', quantity: 'Množství', message: 'Další informace', photo: 'Přiložit fotografii', drawing: 'Přiložit výkres', optional: 'volitelné', privacy: 'Soubory: JPG, PNG, WEBP nebo PDF, každý nejvýše 4 MB.', submit: 'Odeslat výrobní poptávku', sending: 'Odesílání…', successTitle: 'Poptávka byla odeslána', successText: 'Děkujeme. Ozveme se po prvním posouzení.', errorRequired: 'Vyplňte povinná pole.', errorEmail: 'Zadejte platnou e-mailovou adresu.', errorFile: 'Příloha má nesprávný formát nebo přesahuje 4 MB.', errorSend: 'Poptávku se nepodařilo odeslat. Zkuste to znovu nebo nám zavolejte.' },
    about: { title: 'SilvoTech je výrobce', lead: 'Pro B2B zákazníky spojujeme výrobu, výběr materiálu, kontrolu kvality, logistiku a sklad ve Varšavě.', pillars: [
      { title: 'Výroba', text: 'Standardní série a individuálně vyráběné díly.' },
      { title: 'Materiály a technologie', text: 'Volba řešení podle požadavků aplikace.' },
      { title: 'Kontrola kvality', text: 'Kontrola rozměrů, provedení a dohodnutých požadavků.' },
      { title: 'Sklad a logistika', text: 'Dohodnuté zásoby pro pravidelný odběr.' },
    ] },
    productionPage: { title: 'Výroba', lead: 'Jak plánujeme a vyrábíme standardní i zakázkové produkty.', stages: [
      { title: 'Posouzení výrobku', text: 'Vyhodnotíme materiál, geometrii, tolerance a množství.' },
      { title: 'Příprava procesu', text: 'Zvolíme technologii, nástroje a parametry výroby.' },
      { title: 'Extruze a opracování', text: 'Provádíme výrobu a přípravu dílů.' },
      { title: 'Kontrola kvality', text: 'Před odesláním kontrolujeme dohodnuté vlastnosti.' },
      { title: 'Balení', text: 'Balení přizpůsobujeme výrobku a dopravě.' },
      { title: 'Sklad', text: 'Opakovaně dodávané výrobky mohou být na skladě ve Varšavě.' },
    ] },
    docs: { title: 'Kvalita a dokumentace', lead: 'Kontroly a dokumenty stanovujeme podle výrobku, materiálu a použití.', items: [
      { title: 'Kontrola rozměrů', text: 'Ověření podle dohodnutých parametrů.' },
      { title: 'Identifikace materiálu', text: 'Výběr a potvrzení materiálu pro konkrétní použití.' },
      { title: 'Dokumentace', text: 'Prohlášení, výsledky zkoušek nebo specifikace podle dohody.' },
      { title: 'Zkušební vzorek', text: 'V případě potřeby připravíme vzorek před sériovou výrobou.' },
    ] },
    footer: { summary: 'Výroba a pravidelné dodávky pro B2B zákazníky v Polsku a Evropě.', company: 'Společnost', offer: 'Možnosti', contact: 'Kontakt', rights: 'Všechna práva vyhrazena.', privacy: 'Ochrana osobních údajů' },
  },
  sk: {
    nav: { home: 'Úvod', products: 'Možnosti', production: 'Výroba', about: 'O nás', cooperation: 'Spolupráca', documents: 'Kvalita', contact: 'Kontakt', cta: 'Dopytovať výrobu', menu: 'Otvoriť menu', language: 'Vybrať jazyk' },
    hero: { eyebrow: 'B2B výroba podľa vašich požiadaviek', title: 'Výrobca silikónových, gumových a plastových výrobkov', lead: 'Hadice, tesnenia, profily a zákazkové diely podľa vzorky, rozmerov alebo výkresu. Opíšte použitie a preveríme možnosť výroby.', proof: 'Priama výroba • Zákazkové riešenia • Sklad vo Varšave', primary: 'Odoslať dopyt', secondary: 'Zobraziť možnosti' },
    products: { label: 'Čo vyrábame', title: 'Príklady skupín výrobkov', lead: 'Ide o príklady našich možností, nie o uzavretý katalóg. Rozmery, materiál a dokumentáciu spresňujeme pre každé použitie.', items: [
      { title: 'Hadice a vedenia', text: 'Silikónové, gumové a technické. Štandardné alebo podľa špecifikácie.' },
      { title: 'Tesnenia', text: 'Zo silikónu, gumy, EPDM a NBR. Výroba podľa vzorky alebo výkresu.' },
      { title: 'Profily', text: 'Silikónové, gumové a EPDM profily vrátane individuálnych prierezov.' },
      { title: 'Dosky a pláty', text: 'Materiály s dohodnutou hrúbkou, tvrdosťou a rozmermi.' },
      { title: 'Technické diely', text: 'Individuálne diely podľa požiadaviek konkrétnej aplikácie.' },
      { title: 'Plastové diely', text: 'Výrobky podľa technických požiadaviek zákazníka.' },
      { title: 'Zákazková výroba', text: 'Preveríme aj výrobky mimo štandardného sortimentu.' },
    ], otherTitle: 'Potrebujete iný výrobok?', otherText: 'Pošlite vzorku, fotografiu, rozmery alebo výkres. Preveríme možnosť výroby.', otherCta: 'Preveriť možnosť výroby' },
    materials: { label: 'Materiály', title: 'Materiál podľa prevádzkových podmienok', lead: 'Materiál spresňujeme podľa teploty, média, zaťaženia, prostredia a požadovanej dokumentácie.', items: [
      { title: 'Silikón', text: 'Pružné diely pre technické a teplotne náročné aplikácie.' },
      { title: 'Guma', text: 'Technické výrobky s parametrami podľa konkrétneho použitia.' },
      { title: 'EPDM', text: 'Profily a tesnenia do náročných podmienok prostredia.' },
      { title: 'NBR', text: 'Technické diely aj pre aplikácie s olejmi a palivami.' },
      { title: 'Plasty', text: 'Diely a komponenty podľa technickej dokumentácie.' },
    ] },
    capabilities: { label: 'Výrobné možnosti', title: 'Technológia podľa výrobku', text: 'Posudzujeme geometriu, materiál, tolerancie, pracovné podmienky a množstvo. Podľa toho volíme postup a kontroly.', bullets: ['Extrúzia profilov a hadíc', 'Opracovanie a príprava dielov', 'Výroba podľa vzorky alebo dokumentácie', 'Rozmerová a kvalitatívna kontrola', 'Balenie podľa potrieb zákazníka', 'Sériová výroba a pravidelné dodávky'], cta: 'Pozrieť výrobu' },
    partner: { label: 'Európska spolupráca', title: 'Dodávky firmám v Európe', text: 'Výrobu, kontrolu kvality a logistiku koordinujeme s jednou kontaktnou osobou v SilvoTech.', materials: ['Silikón', 'Guma', 'EPDM', 'NBR', 'Plasty', 'Preveríme možnosť výroby'] },
    process: { label: 'Spolupráca', title: 'Od vzorky k pravidelným dodávkam', steps: [
      { title: 'Dopyt', text: 'Pošlete vzorku, fotografiu, rozmery alebo výkres.' },
      { title: 'Posúdenie', text: 'Preveríme realizovateľnosť a pripravíme kalkuláciu.' },
      { title: 'Ponuka a vzorka', text: 'Pripravíme ponuku a podľa potreby skúšobnú vzorku.' },
      { title: 'Výroba', text: 'Po schválení naplánujeme a spustíme výrobu.' },
      { title: 'Sklad', text: 'Pri pravidelnom odbere môžeme držať zásobu vo Varšave.' },
      { title: 'Dodávka', text: 'Dohodnutý skladový tovar možno odoslať aj do 24 hodín.' },
    ] },
    form: { label: 'B2B dopyt', title: 'Dopytovať u výrobcu', lead: 'Opíšte výrobok alebo priložte fotografiu a výkres. Preveríme možnosť výroby a prípadné technické otázky.', company: 'Firma', name: 'Meno a priezvisko', email: 'E-mail', phone: 'Telefón', product: 'Výrobok', material: 'Materiál', dimensions: 'Rozmery', quantity: 'Množstvo', message: 'Ďalšie informácie', photo: 'Priložiť fotografiu', drawing: 'Priložiť výkres', optional: 'voliteľné', privacy: 'Súbory: JPG, PNG, WEBP alebo PDF, každý najviac 4 MB.', submit: 'Odoslať výrobný dopyt', sending: 'Odosielanie…', successTitle: 'Dopyt bol odoslaný', successText: 'Ďakujeme. Ozveme sa po prvom posúdení.', errorRequired: 'Vyplňte povinné polia.', errorEmail: 'Zadajte platnú e-mailovú adresu.', errorFile: 'Príloha má nesprávny formát alebo presahuje 4 MB.', errorSend: 'Dopyt sa nepodarilo odoslať. Skúste to znova alebo nám zavolajte.' },
    about: { title: 'SilvoTech je výrobca', lead: 'Pre B2B zákazníkov spájame výrobu, výber materiálu, kontrolu kvality, logistiku a sklad vo Varšave.', pillars: [
      { title: 'Výroba', text: 'Štandardné série a individuálne vyrábané diely.' },
      { title: 'Materiály a technológie', text: 'Voľba riešenia podľa požiadaviek aplikácie.' },
      { title: 'Kontrola kvality', text: 'Kontrola rozmerov, vyhotovenia a dohodnutých požiadaviek.' },
      { title: 'Sklad a logistika', text: 'Dohodnuté zásoby pri pravidelnom odbere.' },
    ] },
    productionPage: { title: 'Výroba', lead: 'Ako plánujeme a vyrábame štandardné aj zákazkové produkty.', stages: [
      { title: 'Posúdenie výrobku', text: 'Vyhodnotíme materiál, geometriu, tolerancie a množstvo.' },
      { title: 'Príprava procesu', text: 'Zvolíme technológiu, nástroje a parametre výroby.' },
      { title: 'Extrúzia a opracovanie', text: 'Vykonávame výrobu a prípravu dielov.' },
      { title: 'Kontrola kvality', text: 'Pred odoslaním kontrolujeme dohodnuté vlastnosti.' },
      { title: 'Balenie', text: 'Balenie prispôsobujeme výrobku a doprave.' },
      { title: 'Sklad', text: 'Opakovane dodávané výrobky môžu byť na sklade vo Varšave.' },
    ] },
    docs: { title: 'Kvalita a dokumentácia', lead: 'Kontroly a dokumenty určujeme podľa výrobku, materiálu a použitia.', items: [
      { title: 'Kontrola rozmerov', text: 'Overenie podľa dohodnutých parametrov.' },
      { title: 'Identifikácia materiálu', text: 'Výber a potvrdenie materiálu na konkrétne použitie.' },
      { title: 'Dokumentácia', text: 'Vyhlásenia, výsledky skúšok alebo špecifikácie podľa dohody.' },
      { title: 'Skúšobná vzorka', text: 'V prípade potreby pripravíme vzorku pred sériovou výrobou.' },
    ] },
    footer: { summary: 'Výroba a pravidelné dodávky pre B2B zákazníkov v Poľsku a Európe.', company: 'Spoločnosť', offer: 'Možnosti', contact: 'Kontakt', rights: 'Všetky práva vyhradené.', privacy: 'Ochrana osobných údajov' },
  },
};

export function completeSiteCopy(locale: Locale, base: SiteCopy): SiteCopy {
  return { ...base, ...overrides[locale] };
}
