import type { Locale } from './i18n';
import { completeSiteCopy } from './localized-content';

type Item = { title: string; text: string; image?: string; bullets?: string[] };
type Step = { title: string; text: string };

export type SiteCopy = {
  meta: { title: string; description: string };
  nav: { home: string; products: string; production: string; about: string; cooperation: string; documents: string; contact: string; cta: string; menu: string; language: string };
  topbar: string;
  hero: { eyebrow: string; title: string; lead: string; proof: string; primary: string; secondary: string };
  factory: { label: string; title: string; text: string; facts: string[] };
  products: { label: string; title: string; lead: string; items: Item[]; otherTitle: string; otherText: string; otherCta: string };
  materials: { label: string; title: string; lead: string; items: Item[] };
  capabilities: { label: string; title: string; text: string; bullets: string[]; cta: string };
  custom: { label: string; title: string; lead: string; inputs: string[]; cta: string };
  partner: { label: string; title: string; text: string; materials: string[] };
  warehouse: { label: string; title: string; text1: string; text2: string; cta: string };
  process: { label: string; title: string; steps: Step[] };
  benefits: { label: string; title: string; items: Item[] };
  form: { label: string; title: string; lead: string; company: string; name: string; email: string; phone: string; product: string; material: string; dimensions: string; quantity: string; message: string; photo: string; drawing: string; optional: string; privacy: string; submit: string; sending: string; successTitle: string; successText: string; errorRequired: string; errorEmail: string; errorFile: string; errorSend: string };
  about: { title: string; lead: string; pillars: Item[] };
  productionPage: { title: string; lead: string; stages: Item[] };
  docs: { title: string; lead: string; items: Item[] };
  cooperationPage: { title: string; lead: string };
  footer: { summary: string; company: string; offer: string; contact: string; rights: string; privacy: string };
};

const images = {
  range: '/media/product-range.webp',
  capabilities: '/media/product-capabilities.webp',
  sheets: '/media/material-sheets.webp',
  profile: '/media/hero-production-line.webp',
  machine: '/media/machine-detail.webp',
  line: '/media/machine-line.webp',
  warehouse: '/media/warehouse-racks.webp',
  warehouse2: '/media/warehouse-floor.webp',
};

const pl: SiteCopy = {
  meta: { title: 'SilvoTech — producent wyrobów silikonowych, gumowych i z tworzyw sztucznych', description: 'Bezpośredni producent wyrobów z silikonu, gumy, EPDM, NBR i tworzyw sztucznych. Produkcja według próbki, wymiarów lub rysunku. Magazyn w Warszawie.' },
  nav: { home: 'Strona główna', products: 'Możliwości', production: 'Produkcja', about: 'O nas', cooperation: 'Współpraca', documents: 'Jakość', contact: 'Kontakt', cta: 'Zapytaj o produkcję', menu: 'Otwórz menu', language: 'Wybierz język' },
  topbar: 'Bezpośrednia produkcja · Indywidualne wykonanie · Magazyn w Warszawie',
  hero: { eyebrow: 'Produkcja B2B według Twoich wymagań', title: 'Producent wyrobów silikonowych, gumowych i z tworzyw sztucznych', lead: 'Węże, uszczelki, profile i detale wykonywane według próbki, wymiarów lub rysunku. Opisz zastosowanie, a sprawdzimy możliwość realizacji.', proof: 'Bezpośrednia produkcja • Szerokie możliwości wykonania • Magazyn w Warszawie', primary: 'Wyślij zapytanie', secondary: 'Zobacz możliwości' },
  factory: { label: 'Bezpośrednio z fabryki', title: 'Produkcja, nie zamknięty katalog', text: 'SilvoTech produkuje wyroby silikonowe, gumowe i z tworzyw sztucznych. Realizujemy produkty standardowe oraz indywidualne elementy wykonywane według próbki, wzoru, wymiarów lub dokumentacji technicznej.', facts: ['Produkcja dla firm', 'Wykonanie indywidualne', 'Wiele grup materiałowych', 'Logistyka z Warszawy'] },
  products: { label: 'Co produkujemy', title: 'Przykładowe grupy wyrobów', lead: 'To przykłady naszych możliwości, a nie zamknięty katalog. Wymiary, materiał i dokumentację ustalamy dla konkretnego zastosowania.', items: [
    { title: 'Węże i przewody', text: 'Silikonowe, gumowe i techniczne. Standardowe lub wykonywane według specyfikacji.', image: images.range },
    { title: 'Uszczelki', text: 'Silikon, guma, EPDM i NBR. Produkcja według próbki lub rysunku.', image: images.capabilities },
    { title: 'Profile', text: 'Profile silikonowe, gumowe i EPDM, także w indywidualnych przekrojach.', image: images.profile },
    { title: 'Arkusze i płyty', text: 'Materiały o różnych grubościach, twardościach i wymiarach.', image: images.sheets },
    { title: 'Elementy techniczne', text: 'Indywidualne detale wykonywane zgodnie z parametrami aplikacji.', image: images.capabilities },
    { title: 'Elementy z tworzyw sztucznych', text: 'Produkty wykonywane zgodnie z wymaganiami technicznymi klienta.', image: images.range },
    { title: 'Produkcja indywidualna', text: 'Najważniejsza możliwość: realizacja produktu spoza standardowego asortymentu.', image: images.machine },
  ], otherTitle: 'Masz inny produkt?', otherText: 'Wyślij próbkę, zdjęcie, wymiar lub rysunek techniczny. Sprawdzimy możliwość jego realizacji.', otherCta: 'Sprawdź możliwość realizacji' },
  materials: { label: 'Materiały', title: 'Dobieramy materiał do warunków pracy', lead: 'Zakres materiału potwierdzamy na podstawie temperatury, medium, obciążeń, środowiska pracy i wymaganej dokumentacji.', items: [
    { title: 'Silikon', text: 'Elastyczne elementy do zastosowań technicznych i wymagających stabilności temperaturowej.', image: images.range },
    { title: 'Guma', text: 'Wyroby techniczne o parametrach dobieranych do konkretnej aplikacji.', image: images.capabilities },
    { title: 'EPDM', text: 'Profile i uszczelnienia do pracy w wymagających warunkach środowiskowych.', image: images.profile },
    { title: 'NBR', text: 'Elementy techniczne dobierane m.in. do kontaktu z olejami i paliwami.', image: images.capabilities },
    { title: 'Tworzywa sztuczne', text: 'Detale i komponenty wykonywane zgodnie z dokumentacją techniczną.', image: images.sheets },
  ] },
  capabilities: { label: 'Możliwości produkcyjne', title: 'Technologia podporządkowana produktowi', text: 'Analizujemy geometrię, materiał, tolerancje, warunki pracy i planowany wolumen. Dobieramy proces oraz sposób kontroli do konkretnego zamówienia.', bullets: ['Ekstruzja profili i przewodów', 'Obróbka i przygotowanie detali', 'Produkcja według wzoru lub dokumentacji', 'Kontrola wymiarów i jakości', 'Pakowanie pod potrzeby odbiorcy', 'Produkcja seryjna i powtarzalne dostawy'], cta: 'Zobacz produkcję' },
  custom: { label: 'Produkcja na zamówienie', title: 'Nie ograniczamy się do standardowego asortymentu', lead: 'Możemy rozpocząć analizę produktu nawet wtedy, gdy nie posiadasz kompletnej dokumentacji technicznej.', inputs: ['Próbka', 'Wzór', 'Zdjęcie', 'Wymiary', 'Przekrój', 'Rysunek techniczny', 'Dokumentacja techniczna'], cta: 'Wyślij zapytanie produkcyjne' },
  partner: { label: 'Obsługa europejska', title: 'Dostawy dla firm w Polsce i Europie', text: 'Koordynujemy produkcję, kontrolę i logistykę w jednym modelu współpracy, z jednym kontaktem po stronie SilvoTech.', materials: ['Silikon', 'Guma', 'EPDM', 'NBR', 'Tworzywa sztuczne', 'Sprawdzimy możliwość realizacji'] },
  warehouse: { label: 'Logistyka B2B', title: 'Produkcja + magazyn w Warszawie', text1: 'Dla klientów posiadających regularne zapotrzebowanie możemy przygotować bezpłatny zapas produktów zarezerwowany dla konkretnej firmy.', text2: 'Dzięki temu uzgodniony produkt może być dostępny w naszym magazynie w Warszawie i wysłany nawet w ciągu 24 godzin.', cta: 'Zapytaj o zapas magazynowy' },
  process: { label: 'Model współpracy', title: 'Od próbki do regularnych dostaw', steps: [
    { title: 'Zapytanie', text: 'Przesyłasz próbkę, zdjęcie, wymiar lub rysunek.' },
    { title: 'Analiza', text: 'Sprawdzamy możliwości wykonania i przygotowujemy kalkulację.' },
    { title: 'Oferta i próbka', text: 'Przygotowujemy ofertę oraz próbkę do testów, jeśli jest potrzebna.' },
    { title: 'Produkcja', text: 'Po akceptacji produktu planujemy i uruchamiamy produkcję.' },
    { title: 'Magazyn', text: 'Dla regularnych klientów możemy przygotować zapas w Warszawie.' },
    { title: 'Dostawa', text: 'Uzgodniony zapas może być wysyłany nawet w ciągu 24 godzin.' },
  ] },
  benefits: { label: 'Współpraca bez pośredników', title: 'Dlaczego bezpośrednio z producentem?', items: [
    { title: 'Bezpośrednia produkcja', text: 'Bez dodatkowych ogniw pośrednich.' },
    { title: 'Elastyczne wykonanie', text: 'Realizacja produktów według indywidualnej specyfikacji.' },
    { title: 'Szeroki zakres materiałów', text: 'Silikon, guma, EPDM, NBR i tworzywa sztuczne.' },
    { title: 'Produkcja według próbki', text: 'Możemy rozpocząć od istniejącego produktu klienta.' },
    { title: 'Konkurencyjne warunki', text: 'Bezpośrednia współpraca pozwala przygotować korzystne warunki B2B.' },
    { title: 'Magazyn w Polsce', text: 'Warszawski magazyn przyspiesza obsługę uzgodnionych zapasów.' },
  ] },
  form: { label: 'Zapytanie B2B', title: 'Zapytaj producenta', lead: 'Opisz produkt lub załącz zdjęcie i rysunek. Ocenimy możliwość realizacji i wrócimy z pytaniami technicznymi.', company: 'Firma', name: 'Imię i nazwisko', email: 'E-mail', phone: 'Telefon', product: 'Produkt', material: 'Materiał', dimensions: 'Wymiary', quantity: 'Ilość', message: 'Dodatkowe informacje', photo: 'Załącz zdjęcie', drawing: 'Załącz rysunek techniczny', optional: 'opcjonalnie', privacy: 'Pliki: JPG, PNG, WEBP lub PDF, maks. 4 MB każdy.', submit: 'Wyślij zapytanie do producenta', sending: 'Wysyłanie…', successTitle: 'Zapytanie zostało wysłane', successText: 'Dziękujemy. Skontaktujemy się po wstępnej analizie.', errorRequired: 'Uzupełnij wymagane pola.', errorEmail: 'Podaj poprawny adres e-mail.', errorFile: 'Załączony plik ma nieprawidłowy format lub przekracza 4 MB.', errorSend: 'Nie udało się wysłać zapytania. Spróbuj ponownie lub skontaktuj się telefonicznie.' },
  about: { title: 'SilvoTech to producent', lead: 'Łączymy produkcję, dobór materiału, kontrolę jakości, logistykę oraz magazyn w Warszawie w jednym modelu obsługi B2B.', pillars: [
    { title: 'Produkcja', text: 'Standardowe serie i elementy wykonywane indywidualnie.', image: images.line },
    { title: 'Materiały i technologie', text: 'Dobór rozwiązania do parametrów aplikacji.', image: images.machine },
    { title: 'Kontrola jakości', text: 'Kontrola wymiarów, wykonania i zgodności zamówienia.', image: images.capabilities },
    { title: 'Magazyn i logistyka', text: 'Uzgodnione zapasy dla regularnych odbiorców.', image: images.warehouse2 },
  ] },
  productionPage: { title: 'Produkcja', lead: 'Zobacz zaplecze, proces i sposób realizacji produktów standardowych oraz indywidualnych.', stages: [
    { title: 'Analiza produktu', text: 'Oceniamy materiał, geometrię, tolerancje i wolumen.', image: images.range },
    { title: 'Przygotowanie procesu', text: 'Dobieramy technologię, narzędzia i parametry produkcji.', image: images.machine },
    { title: 'Ekstruzja i obróbka', text: 'Prowadzimy proces produkcyjny oraz przygotowanie detali.', image: images.profile },
    { title: 'Kontrola jakości', text: 'Sprawdzamy wykonanie przed przygotowaniem wysyłki.', image: images.line },
    { title: 'Pakowanie', text: 'Sposób pakowania dostosowujemy do produktu i logistyki klienta.', image: images.capabilities },
    { title: 'Magazyn', text: 'Dla uzgodnionych produktów możemy utrzymywać zapas w Warszawie.', image: images.warehouse },
  ] },
  docs: { title: 'Jakość i dokumentacja', lead: 'Zakres kontroli i dokumentów ustalamy zgodnie z produktem, materiałem i wymaganiami aplikacji.', items: [
    { title: 'Kontrola wymiarów', text: 'Weryfikacja zgodności produktu z uzgodnionymi parametrami.' },
    { title: 'Identyfikacja materiału', text: 'Dobór i potwierdzenie materiału dla konkretnego zastosowania.' },
    { title: 'Dokumentacja', text: 'Deklaracje, wyniki badań lub specyfikacje przekazujemy w uzgodnionym zakresie.' },
    { title: 'Próbka do testów', text: 'Jeśli projekt tego wymaga, przygotowujemy próbkę przed produkcją seryjną.' },
  ] },
  cooperationPage: { title: 'Współpraca B2B', lead: 'Od pierwszej próbki do produkcji seryjnej, zapasu magazynowego i regularnych dostaw.' },
  footer: { summary: 'Produkcja i regularne dostawy dla klientów B2B w Polsce i Europie.', company: 'Firma', offer: 'Możliwości', contact: 'Kontakt', rights: 'Wszelkie prawa zastrzeżone.', privacy: 'Polityka prywatności' },
};

const en: SiteCopy = {
  ...pl,
  meta: { title: 'SilvoTech — silicone, rubber and plastic products manufacturer', description: 'Direct manufacturer of silicone, rubber, EPDM, NBR and plastic products. Production from samples, dimensions or technical drawings. Warehouse in Warsaw.' },
  nav: { home: 'Home', products: 'Capabilities', production: 'Production', about: 'About us', cooperation: 'Cooperation', documents: 'Quality', contact: 'Contact', cta: 'Ask about production', menu: 'Open menu', language: 'Choose language' },
  topbar: 'Direct production · Custom manufacturing · Warehouse in Warsaw',
  hero: { eyebrow: 'B2B manufacturing to your requirements', title: 'Manufacturer of silicone, rubber and plastic products', lead: 'Hoses, gaskets, profiles and custom parts made from a sample, dimensions or drawing. Tell us about the application and we will assess feasibility.', proof: 'Direct production • Broad manufacturing capabilities • Warehouse in Warsaw', primary: 'Send an enquiry', secondary: 'Explore capabilities' },
  factory: { label: 'Direct from the factory', title: 'Manufacturing, not a closed catalogue', text: 'SilvoTech manufactures silicone, rubber and plastic products. We supply standard products and custom components made from samples, patterns, dimensions or technical documentation.', facts: ['B2B manufacturing', 'Custom execution', 'Multiple material groups', 'Logistics from Warsaw'] },
  products: { ...pl.products, label: 'What we manufacture', title: 'Example product groups', lead: 'This is not a closed catalogue. We show our main groups and assess every custom part individually.', otherTitle: 'Need a different product?', otherText: 'Send a sample, photo, dimensions or technical drawing. We will check whether it can be made.', otherCta: 'Check feasibility', items: [
    { title: 'Hoses and tubing', text: 'Silicone, rubber and technical tubing, standard or made to specification.', image: images.range }, { title: 'Gaskets', text: 'Silicone, rubber, EPDM and NBR, made from samples or drawings.', image: images.capabilities }, { title: 'Profiles', text: 'Silicone, rubber and EPDM profiles, including custom cross-sections.', image: images.profile }, { title: 'Sheets and plates', text: 'Materials in different thicknesses, hardnesses and dimensions.', image: images.sheets }, { title: 'Technical components', text: 'Custom parts made for the operating parameters of the application.', image: images.capabilities }, { title: 'Plastic components', text: 'Products manufactured to the customer’s technical requirements.', image: images.range }, { title: 'Custom manufacturing', text: 'Our key capability: producing items outside a standard range.', image: images.machine },
  ] },
  materials: { ...pl.materials, label: 'Materials', title: 'Material matched to operating conditions', lead: 'We confirm the material based on temperature, medium, load, environment and required documentation.', items: [
    { title: 'Silicone', text: 'Flexible components for technical and temperature-sensitive applications.', image: images.range }, { title: 'Rubber', text: 'Technical products specified for the application.', image: images.capabilities }, { title: 'EPDM', text: 'Profiles and seals for demanding environmental conditions.', image: images.profile }, { title: 'NBR', text: 'Technical parts selected for applications including oils and fuels.', image: images.capabilities }, { title: 'Plastics', text: 'Parts and components made to technical documentation.', image: images.sheets },
  ] },
  capabilities: { ...pl.capabilities, label: 'Manufacturing capabilities', title: 'Technology selected for the product', text: 'We analyse geometry, material, tolerances, operating conditions and volume, then select the process and quality controls.', bullets: ['Profile and hose extrusion', 'Part processing and finishing', 'Production from samples or documentation', 'Dimensional and quality control', 'Customer-specific packaging', 'Series production and recurring deliveries'], cta: 'Explore production' },
  custom: { label: 'Custom manufacturing', title: 'We are not limited to a standard range', lead: 'We can start the product analysis even without complete technical documentation.', inputs: ['Sample', 'Pattern', 'Photo', 'Dimensions', 'Cross-section', 'Technical drawing', 'Technical documentation'], cta: 'Send a manufacturing enquiry' },
  partner: { label: 'European service', title: 'Deliveries for companies across Europe', text: 'We coordinate manufacturing, quality control and logistics through one cooperation model and one SilvoTech contact.', materials: ['Silicone', 'Rubber', 'EPDM', 'NBR', 'Plastics', 'We will check feasibility'] },
  warehouse: { label: 'B2B logistics', title: 'Production + warehouse in Warsaw', text1: 'For customers with recurring demand, we can prepare a free stock reserved for a specific company.', text2: 'An agreed product can then be available in our Warsaw warehouse and dispatched within as little as 24 hours.', cta: 'Ask about reserved stock' },
  process: { label: 'Cooperation model', title: 'From sample to recurring deliveries', steps: [{ title: 'Enquiry', text: 'You send a sample, photo, dimension or drawing.' }, { title: 'Analysis', text: 'We check feasibility and prepare a calculation.' }, { title: 'Offer and sample', text: 'We prepare an offer and a test sample where needed.' }, { title: 'Production', text: 'After approval, we plan and start production.' }, { title: 'Warehouse', text: 'For recurring customers, we can reserve stock in Warsaw.' }, { title: 'Delivery', text: 'Agreed stock can be dispatched within as little as 24 hours.' }] },
  benefits: { ...pl.benefits, label: 'Direct cooperation', title: 'Why work directly with a manufacturer?', items: [{ title: 'Direct production', text: 'No unnecessary intermediary layers.' }, { title: 'Flexible execution', text: 'Products made to an individual specification.' }, { title: 'Broad material range', text: 'Silicone, rubber, EPDM, NBR and plastics.' }, { title: 'Production from a sample', text: 'We can start from your existing product.' }, { title: 'Competitive terms', text: 'Direct cooperation supports effective B2B purchasing terms.' }, { title: 'Warehouse in Poland', text: 'The Warsaw warehouse speeds up agreed stock deliveries.' }] },
  form: { ...pl.form, label: 'B2B enquiry', title: 'Ask the manufacturer', lead: 'Describe the product or attach a photo and drawing. We will assess feasibility and return with technical questions.', company: 'Company', name: 'Full name', email: 'E-mail', phone: 'Phone', product: 'Product', material: 'Material', dimensions: 'Dimensions', quantity: 'Quantity', message: 'Additional information', photo: 'Attach photo', drawing: 'Attach technical drawing', optional: 'optional', privacy: 'Files: JPG, PNG, WEBP or PDF, max. 4 MB each.', submit: 'Send enquiry to manufacturer', sending: 'Sending…', successTitle: 'Enquiry sent', successText: 'Thank you. We will contact you after the initial assessment.', errorRequired: 'Complete the required fields.', errorEmail: 'Enter a valid e-mail address.', errorFile: 'The attachment has an invalid format or exceeds 4 MB.', errorSend: 'We could not send the enquiry. Try again or call us.' },
  about: { ...pl.about, title: 'SilvoTech is a manufacturer', lead: 'We combine production, material selection, quality control, logistics and a Warsaw warehouse in one B2B service model.' },
  productionPage: { ...pl.productionPage, title: 'Production', lead: 'See the facilities, process and delivery model behind standard and custom products.' },
  docs: { ...pl.docs, title: 'Quality and documentation', lead: 'Quality controls and documentation are agreed for the product, material and application.' },
  cooperationPage: { title: 'B2B cooperation', lead: 'From the first sample through series production, reserved stock and recurring deliveries.' },
  footer: { summary: 'Manufacturer of silicone, rubber and plastic products. Standard and custom B2B production.', company: 'Company', offer: 'Capabilities', contact: 'Contact', rights: 'All rights reserved.', privacy: 'Privacy policy' },
};

// Concise localized variants keep the same industrial content model.
const de: SiteCopy = { ...en, meta: { title: 'SilvoTech — Hersteller von Silikon-, Gummi- und Kunststoffprodukten', description: 'Direkter Hersteller von Produkten aus Silikon, Gummi, EPDM, NBR und Kunststoff. Fertigung nach Muster, Maß oder Zeichnung. Lager in Warschau.' }, nav: { home: 'Startseite', products: 'Produkte & Materialien', production: 'Produktion', about: 'Über uns', cooperation: 'Zusammenarbeit', documents: 'Qualität', contact: 'Kontakt', cta: 'Produktion anfragen', menu: 'Menü öffnen', language: 'Sprache wählen' }, topbar: 'Direkte Produktion · Sonderanfertigung · Lager in Warschau', hero: { eyebrow: 'Europäischer B2B-Hersteller', title: 'Hersteller von Silikon-, Gummi- und Kunststoffprodukten', lead: 'Standard- und Sonderfertigung nach Muster, Abmessungen oder technischer Zeichnung.', proof: 'Direkte Produktion • Breite Fertigungsmöglichkeiten • Lager in Warschau', primary: 'Produktion anfragen', secondary: 'Muster / Zeichnung senden' }, factory: { label: 'Direkt ab Werk', title: 'Fertigung statt geschlossenem Katalog', text: 'SilvoTech fertigt Standardprodukte und individuelle Bauteile aus Silikon, Gummi und Kunststoffen nach Muster, Maß oder technischer Dokumentation.', facts: ['B2B-Fertigung', 'Sonderanfertigung', 'Viele Materialgruppen', 'Logistik aus Warschau'] }, custom: { label: 'Sonderfertigung', title: 'Nicht auf Standardsortimente begrenzt', lead: 'Wir können die Produktanalyse auch ohne vollständige technische Dokumentation beginnen.', inputs: ['Muster', 'Vorlage', 'Foto', 'Abmessungen', 'Querschnitt', 'Technische Zeichnung', 'Technische Dokumentation'], cta: 'Fertigungsanfrage senden' }, warehouse: { label: 'B2B-Logistik', title: 'Produktion + Lager in Warschau', text1: 'Für Kunden mit regelmäßigem Bedarf können wir einen kostenlosen, firmenbezogenen Bestand vorbereiten.', text2: 'Abgestimmte Produkte können dann in Warschau verfügbar sein und innerhalb von bis zu 24 Stunden versendet werden.', cta: 'Lagerbestand anfragen' }, form: { ...en.form, label: 'B2B-Anfrage', title: 'Hersteller anfragen', lead: 'Beschreiben Sie das Produkt oder senden Sie Foto und Zeichnung. Wir prüfen die Machbarkeit.', company: 'Unternehmen', name: 'Vor- und Nachname', phone: 'Telefon', product: 'Produkt', material: 'Material', dimensions: 'Abmessungen', quantity: 'Menge', message: 'Zusätzliche Informationen', photo: 'Foto anhängen', drawing: 'Technische Zeichnung anhängen', optional: 'optional', submit: 'Anfrage an Hersteller senden' }, about: { ...en.about, title: 'SilvoTech ist Hersteller', lead: 'Produktion, Materialauswahl, Qualitätskontrolle, Logistik und Lager in Warschau aus einer Hand.' }, productionPage: { ...en.productionPage, title: 'Produktion', lead: 'Anlagen, Prozesse und Abläufe für Standard- und Sonderprodukte.' }, cooperationPage: { title: 'B2B-Zusammenarbeit', lead: 'Vom ersten Muster bis zur Serie, zum Lagerbestand und zu regelmäßigen Lieferungen.' } };
const cz: SiteCopy = { ...en, meta: { title: 'SilvoTech — výrobce silikonových, pryžových a plastových výrobků', description: 'Přímý výrobce výrobků ze silikonu, pryže, EPDM, NBR a plastů. Výroba podle vzorku, rozměrů nebo výkresu. Sklad ve Varšavě.' }, nav: { home: 'Úvod', products: 'Výrobky a materiály', production: 'Výroba', about: 'O nás', cooperation: 'Spolupráce', documents: 'Kvalita', contact: 'Kontakt', cta: 'Poptat výrobu', menu: 'Otevřít menu', language: 'Vybrat jazyk' }, topbar: 'Přímá výroba · Zakázkové provedení · Sklad ve Varšavě', hero: { eyebrow: 'Evropský B2B výrobce', title: 'Výrobce silikonových, pryžových a plastových výrobků', lead: 'Standardní i zakázková výroba podle vzorku, rozměrů nebo technického výkresu.', proof: 'Přímá výroba • Široké možnosti provedení • Sklad ve Varšavě', primary: 'Poptat výrobu', secondary: 'Poslat vzorek / výkres' }, factory: { label: 'Přímo z výroby', title: 'Výroba, ne uzavřený katalog', text: 'SilvoTech vyrábí standardní i individuální díly ze silikonu, pryže a plastů podle vzorku, rozměrů nebo dokumentace.', facts: ['B2B výroba', 'Zakázkové provedení', 'Více skupin materiálů', 'Logistika z Varšavy'] }, custom: { label: 'Zakázková výroba', title: 'Neomezujeme se na standardní sortiment', lead: 'Analýzu výrobku můžeme zahájit i bez kompletní technické dokumentace.', inputs: ['Vzorek', 'Předloha', 'Fotografie', 'Rozměry', 'Průřez', 'Technický výkres', 'Technická dokumentace'], cta: 'Odeslat výrobní poptávku' }, warehouse: { label: 'B2B logistika', title: 'Výroba + sklad ve Varšavě', text1: 'Pro zákazníky s pravidelnou potřebou můžeme připravit bezplatnou zásobu rezervovanou pro konkrétní firmu.', text2: 'Dohodnutý výrobek tak může být dostupný ve Varšavě a odeslán i do 24 hodin.', cta: 'Zeptat se na skladovou zásobu' }, form: { ...en.form, label: 'B2B poptávka', title: 'Zeptejte se výrobce', lead: 'Popište výrobek nebo přiložte fotografii a výkres. Prověříme možnost realizace.', company: 'Firma', name: 'Jméno a příjmení', phone: 'Telefon', product: 'Výrobek', material: 'Materiál', dimensions: 'Rozměry', quantity: 'Množství', message: 'Další informace', photo: 'Přiložit fotografii', drawing: 'Přiložit technický výkres', optional: 'volitelné', submit: 'Odeslat poptávku výrobci' }, about: { ...en.about, title: 'SilvoTech je výrobce', lead: 'Spojujeme výrobu, výběr materiálu, kontrolu kvality, logistiku a sklad ve Varšavě.' }, productionPage: { ...en.productionPage, title: 'Výroba', lead: 'Podívejte se na zázemí a proces standardní i zakázkové výroby.' }, cooperationPage: { title: 'B2B spolupráce', lead: 'Od prvního vzorku přes sériovou výrobu až po sklad a pravidelné dodávky.' } };
const sk: SiteCopy = { ...cz, meta: { title: 'SilvoTech — výrobca silikónových, gumových a plastových výrobkov', description: 'Priamy výrobca výrobkov zo silikónu, gumy, EPDM, NBR a plastov. Výroba podľa vzorky, rozmerov alebo výkresu. Sklad vo Varšave.' }, nav: { home: 'Úvod', products: 'Výrobky a materiály', production: 'Výroba', about: 'O nás', cooperation: 'Spolupráca', documents: 'Kvalita', contact: 'Kontakt', cta: 'Opýtať sa na výrobu', menu: 'Otvoriť menu', language: 'Vybrať jazyk' }, topbar: 'Priama výroba · Zákazkové vyhotovenie · Sklad vo Varšave', hero: { eyebrow: 'Európsky B2B výrobca', title: 'Výrobca silikónových, gumových a plastových výrobkov', lead: 'Štandardná aj zákazková výroba podľa vzorky, rozmerov alebo technického výkresu.', proof: 'Priama výroba • Široké možnosti vyhotovenia • Sklad vo Varšave', primary: 'Opýtať sa na výrobu', secondary: 'Poslať vzorku / výkres' }, factory: { label: 'Priamo z výroby', title: 'Výroba, nie uzavretý katalóg', text: 'SilvoTech vyrába štandardné aj individuálne diely zo silikónu, gumy a plastov podľa vzorky, rozmerov alebo dokumentácie.', facts: ['B2B výroba', 'Zákazkové vyhotovenie', 'Viac skupín materiálov', 'Logistika z Varšavy'] }, custom: { label: 'Zákazková výroba', title: 'Neobmedzujeme sa na štandardný sortiment', lead: 'Analýzu výrobku môžeme začať aj bez kompletnej technickej dokumentácie.', inputs: ['Vzorka', 'Predloha', 'Fotografia', 'Rozmery', 'Prierez', 'Technický výkres', 'Technická dokumentácia'], cta: 'Odoslať výrobný dopyt' }, warehouse: { label: 'B2B logistika', title: 'Výroba + sklad vo Varšave', text1: 'Pre zákazníkov s pravidelnou potrebou môžeme pripraviť bezplatnú zásobu rezervovanú pre konkrétnu firmu.', text2: 'Dohodnutý výrobok tak môže byť dostupný vo Varšave a odoslaný aj do 24 hodín.', cta: 'Opýtať sa na skladovú zásobu' }, form: { ...en.form, label: 'B2B dopyt', title: 'Opýtajte sa výrobcu', lead: 'Opíšte výrobok alebo priložte fotografiu a výkres. Preveríme možnosť realizácie.', company: 'Firma', name: 'Meno a priezvisko', phone: 'Telefón', product: 'Výrobok', material: 'Materiál', dimensions: 'Rozmery', quantity: 'Množstvo', message: 'Ďalšie informácie', photo: 'Priložiť fotografiu', drawing: 'Priložiť technický výkres', optional: 'voliteľné', submit: 'Odoslať dopyt výrobcovi' }, about: { ...en.about, title: 'SilvoTech je výrobca', lead: 'Spájame výrobu, výber materiálu, kontrolu kvality, logistiku a sklad vo Varšave.' }, productionPage: { ...en.productionPage, title: 'Výroba', lead: 'Pozrite si zázemie a proces štandardnej aj zákazkovej výroby.' }, cooperationPage: { title: 'B2B spolupráca', lead: 'Od prvej vzorky cez sériovú výrobu až po sklad a pravidelné dodávky.' } };

const content: Record<Locale, SiteCopy> = { pl, en, de, cz, sk };
export function getSiteCopy(locale: Locale): SiteCopy { return completeSiteCopy(locale, content[locale] ?? pl); }
export { images };
